#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  >&2 echo "WARNING! YOU ARE COMMITTING DIRECTLY TO MASTER!"
fi

type_error_msg="TYPE ERRORS FOUND. Please fix them before committing. This may be because you installed a new version of a dependency including a breaking change."

yarn lint || (echo "$type_error_msg" && exit 1)

